# Run a build every 6 hours to get stats

name: Run speed tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  run-speed-test:
    runs-on: ubuntu-latest
    env:
      CONTEXT: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: default

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm install
        working-directory: default

      - name: Run test-pages
        run: npm run test-pages
        working-directory: default

      - name: Add & commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: live
          file_pattern: _data/results/**/*,_data/results-last-runs.json
          commit_message: "Update results"
          push_options: --force
