# Run a build every 6 hours to get stats

name: Trigger Netlify Build
on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.BUILD_WEBHOOK }}
