# Run a build every 6 hours to get stats

name: Run speed tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  run-speed-test:
    runs-on: ubuntu-latest
    env:
      CONTEXT: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm install

      - name: Run test-pages
        run: npm run test-pages

      - name: Add & commit results
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: "_data"
          message: "Update results"
